"""add kind and score to alerts

Revision ID: 3324f834f933
Revises: 412f778e47be
Create Date: 2026-06-15 04:58:25.479819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3324f834f933'
down_revision: Union[str, None] = '412f778e47be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('kind', sa.String(), server_default='deadline', nullable=False))
    op.add_column('alerts', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'score')
    op.drop_column('alerts', 'kind')
    # ### end Alembic commands ###
