"""add ai_analysis column to tenders

Revision ID: 412f778e47be
Revises: b6d9d1a7b8b3
Create Date: 2026-06-13 22:30:26.536587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412f778e47be'
down_revision: Union[str, None] = 'b6d9d1a7b8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
