"""remove user fk from bids

Revision ID: 8dd0395d38e7
Revises: 9a4f145f0c30
Create Date: 2026-06-10 14:21:37.586986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd0395d38e7'
down_revision: Union[str, None] = '9a4f145f0c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bids_user_id_fkey', 'bids', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('bids_user_id_fkey', 'bids', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
