"""add match score to tenders

Revision ID: 9a4f145f0c30
Revises: 1896c1383e76
Create Date: 2026-06-09 16:43:08.935098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a4f145f0c30'
down_revision: Union[str, None] = '1896c1383e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('match_score', sa.Float(), nullable=True))
    op.add_column('tenders', sa.Column('match_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'match_reasoning')
    op.drop_column('tenders', 'match_score')
    # ### end Alembic commands ###
