"""add alerts table

Revision ID: b4dd78236a50
Revises: b0749820bb47
Create Date: 2026-06-13 22:07:38.030927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dd78236a50'
down_revision: Union[str, None] = 'b0749820bb47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bid_id', sa.String(), nullable=False),
    sa.Column('tender_id', sa.String(), nullable=True),
    sa.Column('tender_title', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('days_left', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('emailed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bid_id', 'threshold', name='uq_alert_bid_threshold')
    )
    op.create_index(op.f('ix_alerts_bid_id'), 'alerts', ['bid_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_bid_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
