"""add ai_analysis column to tenders

Revision ID: b6d9d1a7b8b3
Revises: 7cfb8e41c4c3
Create Date: 2026-06-13 22:30:10.898050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d9d1a7b8b3'
down_revision: Union[str, None] = '7cfb8e41c4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('ai_analysis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'ai_analysis')
    # ### end Alembic commands ###
